---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: worker1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker1
  template:
    metadata:
      labels:
        app: worker1
    spec:
      containers:
        - name: worker1
          image: jeetp2001/workerimg1