apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-1
  namespace: default
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app-1
  templates:
    metadata:
      labels:
        app: nginx-app-1
    spec:
      containers:
      - name: nginx-app1
        image: jeetp2001/nginx-app-img1
        ports:
        - containerPort: 80
